### ISSUE TITLE
不支持SQLite

### ISSUE THREAD

**Issue by yxzwym** [jrotty/soso#1]
SQLSTATE[HY000]: General error: 1 RIGHT and FULL OUTER JOINs are not currently supported
Typecho_Db_Query_Exception: SQLSTATE[HY000]: General error: 1 RIGHT and FULL OUTER JOINs are not currently supported in /var/www/var/Typecho/Db/Adapter/Pdo.php:105
Stack trace:
#0 /var/www/var/Typecho/Db.php(354): Typecho_Db_Adapter_Pdo->query('SELECT typecho_...', Object(PDO), 1, 'SELECT')
#1 /var/www/var/Typecho/Db.php(384): Typecho_Db->query(Object(Typecho_Db_Query), 1)
#2 /var/www/var/Widget/Archive.php(1250): Typecho_Db->fetchAll(Object(Typecho_Db_Query), Array)
#3 /var/www/usr/plugins/Soso/Plugin.php(121): Widget_Archive->query(Object(Typecho_Db_Query))
#4 /var/www/var/Typecho/Plugin.php(489): Soso_Plugin::soso('nginx', Object(Widget_Archive), NULL)
#5 /var/www/var/Widget/Archive.php(1182): Typecho_Plugin->__call('Widget_Archive:...', Array)
#6 /var/www/var/Widget/Archive.php(1368): Widget_Archive->searchHandle(Object(Typecho_Db_Query), true)
#7 /var/www/var/Typecho/Widget.php(221): Widget_Archive->execute()
#8 /var/www/var/Typecho/Router.php(135): Typecho_Widget::widget('Widget_Archive', NULL, Array)
#9 /var/www/index.php(23): Typecho_Router::dispatch()
#10 {main}

**Comment by jrotty** [comment]
一直在用mysql，26年了你可以试试ai支持下
